export interface Department {
    id?: number,
    name: string ,
    address: string ,
    totalRooms: number ,
    totalParking: number ,
    totalBaths: number ,
    internet: number ,
    tv: number ,
    heating: number,
    furnished: number,
    departmentPrice: number,
    departmentStatus: number,
    departmentDesc: string,
    idCommune: string,
    nameCommune?: string,
    departmentImage?: string,
}